// Auto-generated from user_signup_agreement_v3.docx
export const AGREEMENT_PARAGRAPHS: { text: string; isHeading?: boolean; isBold?: boolean }[] = [
  { text: `AGENT NASH — USER SIGN-UP AGREEMENT`, isBold: true },
  { text: `Effective Date: March 30, 2026` },
  { text: `Last Updated: March 30, 2026` },
  { text: `Version: 3.0` },
  { text: `THIS IS A LEGALLY BINDING AGREEMENT. READ IT CAREFULLY BEFORE CREATING AN ACCOUNT OR USING THE PLATFORM.`, isBold: true },
  { text: `This User Sign-Up Agreement (\"Agreement\") is a legally binding contract entered into between Prediction Market Agents (\"Company,\" \"we,\" \"us,\" or \"our\") and you (\"User,\" \"you,\" or \"your\") upon your creation of an account on the Prediction Market Agents platform (example.com) or upon your access to or use of the Platform following the availability of this Agreement.` },
  { text: `INCORPORATION OF TERMS AND CONDITIONS AND PRIVACY POLICY`, isHeading: true, isBold: true },
  { text: `This Agreement expressly incorporates by reference, and must be read together with, the following documents, each of which forms part of your legally binding agreement with Prediction Market Agents (collectively, the \"Agreement Documents\"):` },
  { text: `- Prediction Market Agents Terms and Conditions (Version 2.0), available at example.com/terms (the \"Terms\")` },
  { text: `- Prediction Market Agents Privacy Policy (Version 2.0), available at example.com/privacy (the \"Privacy Policy\")` },
  { text: `- Any applicable Fund documentation, order forms, or supplemental agreements provided to you` },
  { text: `BY CREATING AN ACCOUNT, TAPPING \"I ACCEPT\" OR ANY SIMILAR BUTTON IN THE AGENT NASH APPLICATION, OR BY ACCESSING OR USING THE PLATFORM IN ANY MANNER, YOU CONFIRM THAT YOU HAVE READ, UNDERSTOOD, AND AGREE TO BE LEGALLY BOUND BY ALL AGREEMENT DOCUMENTS, INCLUDING THE TERMS AND CONDITIONS AND PRIVACY POLICY, AS IF EACH WERE SIGNED BY YOU INDIVIDUALLY. YOUR TAP, CLICK, OR OTHER ELECTRONIC ACTION HAS THE SAME LEGAL FORCE AS A HANDWRITTEN SIGNATURE (SEE SECTION 15). IF YOU DO NOT AGREE TO ANY PART OF ANY AGREEMENT DOCUMENT, YOU MUST NOT CREATE AN ACCOUNT AND MUST NOT USE THE PLATFORM.`, isBold: true },
  { text: `In the event of a conflict between this Agreement and the Terms and Conditions, the Terms and Conditions shall prevail unless this Agreement expressly states otherwise. All defined terms used but not defined in this Agreement have the meanings given to them in the Terms and Conditions.` },
  { text: `1. ACCOUNT CREATION AND VERIFICATION`, isHeading: true, isBold: true },
  { text: `1.1. Registration Information. You must provide the following information during registration:`, isHeading: true },
  { text: `- Full legal name (as it appears on government-issued identification)` },
  { text: `- Valid email address that you regularly monitor` },
  { text: `- Secure password meeting our minimum complexity requirements` },
  { text: `- Country and jurisdiction of primary residence` },
  { text: `- Nationality/citizenship (may be required for sanctions screening)` },
  { text: `- Organization or entity name (if applicable)` },
  { text: `- Professional role, title, or capacity (if applicable)` },
  { text: `- Intended use of the Platform (personal, institutional, research, etc.)` },
  { text: `1.2. Accuracy Obligation. You represent and warrant that all registration information is truthful, accurate, current, and complete. You agree to update your information promptly if any details change. Providing false, misleading, outdated, or incomplete information constitutes a material breach of this Agreement and grounds for immediate termination without notice or refund.`, isHeading: true },
  { text: `1.3. Enhanced Verification. We may require additional verification at any time, at our sole discretion, including:`, isHeading: true },
  { text: `- Government-issued photo identification (passport, national ID, driver's license)` },
  { text: `- Proof of residential address (utility bill, bank statement, government correspondence dated within 3 months)` },
  { text: `- Selfie, liveness check, or biometric verification for identity confirmation` },
  { text: `- Accredited investor or qualified purchaser certification (for Fund participation)` },
  { text: `- Institutional authorization (board resolution, power of attorney, corporate registration, certificate of incorporation)` },
  { text: `- Source of funds and source of wealth documentation` },
  { text: `- Tax identification numbers and tax residency certificates` },
  { text: `- Proof of authorization to trade in prediction markets, cryptocurrency, equities, or other Supported Markets in your jurisdiction` },
  { text: `- Enhanced due diligence documentation for high-risk jurisdictions or profiles` },
  { text: `- Any other documentation we deem necessary in our sole discretion` },
  { text: `1.4. Sanctions and AML Screening. Your identity will be screened against international sanctions lists (OFAC SDN List, EU Consolidated List, UK Sanctions List, UN Security Council Consolidated List, and other applicable lists), Politically Exposed Person (PEP) databases, adverse media databases, and law enforcement watchlists. We conduct both initial and ongoing screening. We reserve the right to refuse or terminate any account based on screening results without obligation to disclose specific reasons.`, isHeading: true },
  { text: `1.5. Ongoing Monitoring. We conduct continuous monitoring of your account and activity for compliance with AML/CTF regulations, sanctions requirements, and our internal policies. We may request updated verification documentation at any time. Failure to provide requested documentation within the specified timeframe may result in account suspension or termination.`, isHeading: true },
  { text: `1.6. One Account. One account per individual or legal entity. Operating multiple accounts, sharing accounts, or creating accounts on behalf of unauthorized third parties is strictly prohibited and will result in immediate termination of all associated accounts.`, isHeading: true },
  { text: `1.7. Right to Refuse. We reserve the absolute and unfettered right to refuse registration, reject applications, or revoke approval at any time, without providing any reason or explanation.`, isHeading: true },
  { text: `2. ACCOUNT SECURITY AND CREDENTIAL MANAGEMENT`, isHeading: true, isBold: true },
  { text: `2.1. Your Sole Responsibility. You are solely and exclusively responsible for the security, confidentiality, and proper use of all credentials associated with your account, including your password, all API keys (both Platform API keys and exchange API keys), access tokens, secret keys, session tokens, OAuth tokens, two-factor authentication recovery codes, and any other authentication or authorization mechanisms.`, isHeading: true },
  { text: `2.2. Security Requirements. You agree to:`, isHeading: true },
  { text: `- Use a strong, unique password of at least 12 characters with uppercase, lowercase, numbers, and special characters` },
  { text: `- Never reuse a password from any other service` },
  { text: `- Enable multi-factor authentication (MFA) when available` },
  { text: `- Never share, transfer, publish, email, message, or otherwise disclose your credentials to any person or entity under any circumstances` },
  { text: `- Never store credentials in plaintext, unencrypted files, public code repositories (e.g., GitHub, GitLab), shared documents, screenshots, or any publicly or semi-publicly accessible location` },
  { text: `- Regularly rotate API keys and access tokens (recommended: every 90 days)` },
  { text: `- Use separate API keys for separate integrations and revoke unused keys` },
  { text: `- Log out of shared, public, or borrowed devices after each session` },
  { text: `- Keep all devices used to access the Platform updated with current security patches` },
  { text: `- Immediately notify Prediction Market Agents at hello@example.com if you suspect or discover any unauthorized access, credential compromise, suspicious account activity, or security incident` },
  { text: `2.3. COMPLETE EXCLUSION OF LIABILITY FOR UNAUTHORIZED ACCESS.`, isHeading: true, isBold: true },
  { text: `AGENT NASH SHALL HAVE NO LIABILITY WHATSOEVER, UNDER ANY THEORY OF LIABILITY (INCLUDING CONTRACT, TORT, NEGLIGENCE, STRICT LIABILITY, OR OTHERWISE), FOR ANY LOSSES, DAMAGES, COSTS, OR EXPENSES OF ANY KIND ARISING FROM OR RELATED TO:`, isBold: true },
  { text: `- Unauthorized access to your account, regardless of how such access was obtained` },
  { text: `- Theft, interception, compromise, exposure, or leakage of your credentials through any means, including but not limited to: phishing, spear-phishing, social engineering, pretexting, vishing, smishing, malware, keyloggers, screen scrapers, trojan horses, ransomware, man-in-the-middle attacks, session hijacking, credential stuffing, brute force attacks, dictionary attacks, shoulder surfing, dumpster diving, insider threats, supply chain attacks, zero-day exploits, or any other known or unknown attack vector` },
  { text: `- Your failure to implement or maintain adequate security practices as described in Section 2.2` },
  { text: `- Unauthorized use of your account by any third party, whether or not you authorized their initial access` },
  { text: `- Unauthorized trades, fund transfers, or data access conducted using your compromised credentials` },
  { text: `- Security incidents, data breaches, or vulnerabilities affecting the Platform, our infrastructure providers, third-party exchanges, LLM providers, or any other service in the technology chain` },
  { text: `- Any delay between credential compromise and your discovery and revocation of the compromised credentials` },
  { text: `THIS EXCLUSION APPLIES REGARDLESS OF WHETHER AGENT NASH WAS NEGLIGENT, GROSSLY NEGLIGENT, OR OTHERWISE AT FAULT, AND REGARDLESS OF WHETHER AGENT NASH KNEW OR SHOULD HAVE KNOWN OF THE VULNERABILITY, ATTACK VECTOR, OR SECURITY WEAKNESS. THIS EXCLUSION ALSO APPLIES TO SECURITY INCIDENTS CAUSED IN WHOLE OR IN PART BY DEFECTS, BUGS, OR VULNERABILITIES IN AGENT NASH'S OWN SOFTWARE, INFRASTRUCTURE, OR SECURITY SYSTEMS.`, isBold: true },
  { text: `2.4. Account Suspension. We reserve the right to immediately suspend or restrict your account upon detection or suspicion of: unauthorized access, anomalous activity, credential compromise, Terms violations, regulatory concerns, or any activity threatening Platform integrity. We are not liable for any losses, missed trades, or other consequences resulting from account suspension, regardless of whether the suspicion was ultimately confirmed.`, isHeading: true },
  { text: `3. EXCHANGE ACCOUNT CONNECTIONS AND API KEY MANAGEMENT`, isHeading: true, isBold: true },
  { text: `3.1. Connection Authorization. To use the Platform's Agent deployment and trade execution infrastructure, you may connect your own exchange accounts with Supported Markets by providing API keys or other authentication credentials. By connecting an exchange account, you authorize Prediction Market Agents infrastructure to transmit trade instructions to that exchange on your behalf through your connected API keys, within your configured risk parameters.`, isHeading: true },
  { text: `3.2. Exchange Account Representations. By connecting any exchange account, you represent, warrant, and covenant that:`, isHeading: true },
  { text: `- You are the sole authorized owner, controller, or legally authorized operator of the exchange account` },
  { text: `- You have the unconditional legal right, capacity, and authority to connect the account and authorize automated trading` },
  { text: `- The exchange account is in good standing, fully verified, and compliant with the exchange's terms of service` },
  { text: `- You have configured API key permissions in accordance with Prediction Market Agents's published requirements` },
  { text: `- You have NOT granted trade/write permissions to any other automated service using the same API keys simultaneously` },
  { text: `- You are legally authorized and permitted under the laws of your jurisdiction to maintain the exchange account and conduct the types of trading activity enabled through the Platform` },
  { text: `- You accept full, exclusive, and sole responsibility for all activity conducted through your connected exchange accounts, including all trades, losses, and consequences` },
  { text: `3.3. API KEY SECURITY AND COMPREHENSIVE RISK ACKNOWLEDGMENT.`, isHeading: true, isBold: true },
  { text: `Prediction Market Agents stores exchange API keys and secret keys using AES-256 encryption at rest and transmits them only over TLS-encrypted connections. NOTWITHSTANDING THESE SECURITY MEASURES, YOU EXPRESSLY ACKNOWLEDGE, UNDERSTAND, AND IRREVOCABLY ACCEPT THE FOLLOWING:` },
  { text: `- No encryption system is impenetrable. Encryption algorithms may be broken. Encryption keys may be compromised through software vulnerabilities, side-channel attacks, quantum computing advances, or other means.` },
  { text: `- API keys and credentials stored on the Platform may be exposed, stolen, or intercepted through: software vulnerabilities or bugs in the Platform; zero-day exploits in underlying infrastructure (Vercel, Supabase, Railway, or their sub-processors); data breaches at any point in the technology chain; insider threats or rogue employees; misconfigured security controls; third-party library vulnerabilities; or any other known or unknown attack vector.` },
  { text: `- Compromised API keys could be used by malicious actors to: execute unauthorized trades on your exchange accounts (potentially resulting in total loss of funds); place orders at unfavorable prices to drain your account; withdraw funds from your exchange accounts (if withdrawal permissions were granted); access your exchange account data, trade history, and balances; manipulate your open positions.` },
  { text: `- The time between API key compromise and your discovery/revocation of the key may be substantial, during which unlimited unauthorized activity could occur.` },
  { text: `- Exchange-side security measures (IP whitelisting, rate limits) may not prevent all unauthorized use of compromised keys.` },
  { text: `AGENT NASH SHALL HAVE ABSOLUTELY NO LIABILITY FOR ANY LOSSES, DAMAGES, OR CONSEQUENCES ARISING FROM THE COMPROMISE, THEFT, EXPOSURE, INTERCEPTION, MISUSE, OR UNAUTHORIZED USE OF ANY API KEYS, SECRET KEYS, ACCESS TOKENS, OR OTHER CREDENTIALS STORED ON, PROCESSED BY, OR TRANSMITTED THROUGH THE PLATFORM, REGARDLESS OF THE CAUSE, INCLUDING AGENT NASH'S OWN NEGLIGENCE, GROSS NEGLIGENCE, WILLFUL MISCONDUCT, OR BREACH OF ITS OWN SECURITY PRACTICES.`, isBold: true },
  { text: `3.4. API Key Permission Best Practices. You are STRONGLY advised to:`, isHeading: true },
  { text: `- Grant ONLY the minimum API permissions required (typically: read market data + place trades). NEVER grant withdrawal, transfer, or fund movement permissions to API keys connected to the Platform unless Prediction Market Agents has explicitly documented such a requirement in writing.` },
  { text: `- Enable IP address whitelisting on your exchange API keys where supported, restricting access to Prediction Market Agents's published IP ranges` },
  { text: `- Set exchange-level trading limits, daily loss caps, and position size limits as an independent safety net` },
  { text: `- Create dedicated API keys exclusively for Prediction Market Agents (do not reuse keys from other services)` },
  { text: `- Regularly review API key activity logs on your exchange for unauthorized activity` },
  { text: `- Rotate API keys at least every 90 days` },
  { text: `- Immediately revoke API keys if you suspect any compromise` },
  { text: `3.5. FAILURE TO FOLLOW THESE BEST PRACTICES DOES NOT CREATE ANY LIABILITY FOR AGENT NASH. HOWEVER, FOLLOWING THESE PRACTICES SIGNIFICANTLY REDUCES YOUR RISK EXPOSURE.`, isHeading: true, isBold: true },
  { text: `3.6. Disconnection and Revocation. You may disconnect your exchange account and revoke API keys at any time through: (a) Platform settings; (b) directly on your exchange account; or (c) contacting hello@example.com. Active Agents connected to revoked keys will be halted. Prediction Market Agents is NOT responsible for:`, isHeading: true },
  { text: `- Any open positions at the time of disconnection (you must close these yourself on the exchange)` },
  { text: `- Any trades or unauthorized activity that occurred before you revoked the API key` },
  { text: `- Any exchange-side delays in processing API key revocations or deactivations` },
  { text: `- Any losses incurred during the gap between key compromise and key revocation` },
  { text: `3.7. Third-Party Exchange Risk. AGENT NASH IS NOT AN EXCHANGE AND HAS NO CONTROL OVER THIRD-PARTY EXCHANGES. You acknowledge and accept that Prediction Market Agents has no responsibility or liability for:`, isHeading: true },
  { text: `- Exchange insolvency, bankruptcy, receivership, or fraud` },
  { text: `- Exchange hacks, data breaches, smart contract exploits, or security incidents` },
  { text: `- Exchange downtime, degraded performance, or API outages` },
  { text: `- Changes to exchange APIs, terms of service, fee structures, or policies` },
  { text: `- Exchange account freezes, restrictions, seizures, or terminations` },
  { text: `- Market delistings, event resolution disputes, or settlement failures` },
  { text: `- Withdrawal restrictions, delays, or fund custody issues` },
  { text: `- Regulatory actions against or by the exchange` },
  { text: `- Any other action, omission, failure, or event attributable to any third-party exchange` },
  { text: `4. NOT INVESTMENT ADVICE; NOT A RECOMMENDATION; INDEPENDENT RESEARCH REQUIRED`, isHeading: true, isBold: true },
  { text: `4.1. NO RECOMMENDATIONS. AGENT NASH DOES NOT PROVIDE, AND THE PLATFORM DOES NOT CONSTITUTE, INVESTMENT ADVICE, FINANCIAL ADVICE, TRADING ADVICE, TAX ADVICE, LEGAL ADVICE, REGULATORY GUIDANCE, OR ANY OTHER FORM OF PROFESSIONAL ADVICE OR PERSONAL RECOMMENDATION.`, isHeading: true, isBold: true },
  { text: `4.2. INFORMATIONAL ONLY. ALL CONTENT ON THE PLATFORM, INCLUDING BUT NOT LIMITED TO: BENCHMARK DATA, PERFORMANCE METRICS, RANKINGS, LEADERBOARDS, STRATEGY COMPARISONS, WIN RATES, SHARPE RATIOS, DRAWDOWN DATA, P&L FIGURES, CONFIDENCE SCORES, MARKET ANALYTICS, INSIGHTS, REPORTS, AND ALL OTHER DATA AND VISUALIZATIONS, IS PROVIDED SOLELY FOR INFORMATIONAL, EDUCATIONAL, AND RESEARCH PURPOSES. NONE OF THIS CONTENT IS A RECOMMENDATION, SOLICITATION, OR OFFER TO BUY, SELL, OR HOLD ANY POSITION, ASSET, CONTRACT, OR INSTRUMENT.`, isHeading: true, isBold: true },
  { text: `4.3. NO ENDORSEMENT. The inclusion, display, ranking, or prominence of any Agent, Strategy, market, exchange, or third-party service on the Platform does not constitute an endorsement, recommendation, or guarantee of quality, performance, reliability, safety, or legality. High-ranking Agents may still lose money. Past performance is not indicative of future results.`, isHeading: true },
  { text: `4.4. YOUR OWN RESEARCH. You acknowledge and agree that:`, isHeading: true },
  { text: `- You must conduct your own independent research, analysis, and due diligence before making any trading or investment decision` },
  { text: `- You must not rely solely on Platform Content, Benchmark Data, Agent performance, or any information provided by Prediction Market Agents when making financial decisions` },
  { text: `- You are solely responsible for evaluating the merits and risks of every trade, position, and strategy` },
  { text: `- Prediction Market Agents has no obligation to provide personalized advice, suitability assessments, or risk profiles` },
  { text: `- You should consult qualified, licensed professionals (financial advisors, tax advisors, legal counsel) for advice specific to your circumstances` },
  { text: `4.5. NO FIDUCIARY DUTY. Prediction Market Agents owes no fiduciary duty, duty of care, duty of loyalty, or advisory duty to any User. No relationship created by the Agreement Documents or by your use of the Platform shall be interpreted as creating a fiduciary, advisory, trust, agency, broker-client, investment adviser-client, joint venture, partnership, or employment relationship.`, isHeading: true },
  { text: `4.6. PAST PERFORMANCE DISCLAIMER. PAST PERFORMANCE OF ANY AGENT, STRATEGY, OR FUND IS NOT INDICATIVE OF FUTURE RESULTS. SIMULATED PERFORMANCE (INCLUDING PAPER TRADING AND BACKTESTING) DOES NOT REFLECT ACTUAL MARKET CONDITIONS AND IS NOT A RELIABLE INDICATOR OF LIVE TRADING PERFORMANCE. BENCHMARK DATA MAY CONTAIN ERRORS, OMISSIONS, AND INACCURACIES. RANKINGS AND SCORES MAY CHANGE WITHOUT NOTICE. NO ALGORITHM, MODEL, OR AI SYSTEM CAN GUARANTEE POSITIVE RETURNS.`, isHeading: true, isBold: true },
  { text: `5. JURISDICTIONAL AUTHORIZATION AND REGULATORY COMPLIANCE`, isHeading: true, isBold: true },
  { text: `5.1. YOUR SOLE REGULATORY RESPONSIBILITY. YOU ARE SOLELY AND EXCLUSIVELY RESPONSIBLE FOR DETERMINING WHETHER YOUR USE OF THE PLATFORM AND ALL ASSOCIATED TRADING ACTIVITY IS LAWFUL IN YOUR JURISDICTION. AGENT NASH DOES NOT AND CANNOT PROVIDE LEGAL OR REGULATORY ADVICE. THE AVAILABILITY OF THE PLATFORM IN YOUR JURISDICTION DOES NOT CONSTITUTE A REPRESENTATION THAT YOUR USE IS LAWFUL.`, isHeading: true, isBold: true },
  { text: `5.2. Market-Specific Regulatory Acknowledgments. By using the Platform, you represent, warrant, and covenant that you have independently verified and confirmed that you are legally authorized and permitted under all applicable laws, regulations, and rules in your jurisdiction to:`, isHeading: true },
  { text: `5.2.1. Prediction Markets`, isHeading: true },
  { text: `- Participate in, trade on, and hold positions on prediction markets (including but not limited to Polymarket, Kalshi, and similar platforms)` },
  { text: `- Use automated or AI-driven systems to trade on prediction markets` },
  { text: `- You understand that prediction markets may be classified as gambling, derivatives, swaps, binary options, or regulated financial instruments in certain jurisdictions, and that trading them may be restricted, require licensing, or be prohibited entirely` },
  { text: `- You have obtained any required licenses, registrations, or approvals to participate in prediction markets in your jurisdiction` },
  { text: `5.2.2. Cryptocurrency and Digital Assets`, isHeading: true },
  { text: `- Buy, sell, hold, and trade cryptocurrency and digital assets on centralized and decentralized exchanges` },
  { text: `- Use automated or AI-driven systems to trade cryptocurrency` },
  { text: `- You understand that cryptocurrency regulation varies dramatically by jurisdiction and may include registration requirements, tax reporting obligations, capital controls, and outright bans` },
  { text: `- You comply with all applicable virtual asset service provider (VASP) regulations and travel rule requirements` },
  { text: `5.2.3. Equities and Securities`, isHeading: true },
  { text: `- Buy, sell, and trade equities, securities, and related instruments on regulated exchanges` },
  { text: `- Use automated or algorithmic trading systems for securities trading` },
  { text: `- You comply with all applicable securities laws, including registration, disclosure, insider trading, and market manipulation prohibitions` },
  { text: `- You understand that algorithmic and AI trading may be subject to specific regulations (e.g., MiFID II in the EU, Regulation SCI in the US)` },
  { text: `5.2.4. Derivatives, Futures, and Options`, isHeading: true },
  { text: `- Trade derivatives, futures, options, swaps, and related instruments where applicable` },
  { text: `- You have any required qualifications or certifications for derivatives trading in your jurisdiction` },
  { text: `5.2.5. Sports Betting and Fantasy Sports`, isHeading: true },
  { text: `- Participate in sports betting and fantasy sports platforms where the Platform integrates such markets` },
  { text: `- You are located in a jurisdiction where such activity is legal and you meet all eligibility requirements` },
  { text: `5.3. Prohibited Jurisdictions and Sanctions Compliance. You represent and warrant that:`, isHeading: true },
  { text: `- You are NOT located in, a national of, a resident of, or ordinarily resident in any country or territory subject to comprehensive U.S. (OFAC), EU, UK, or UN sanctions, including but not limited to: Cuba, Iran, North Korea, Syria, and the Crimea, Donetsk, and Luhansk regions of Ukraine` },
  { text: `- You are NOT listed on any U.S. (SDN List, Entity List, Denied Persons List, Unverified List), EU, UK, or UN sanctions list, denied party list, restricted party list, or similar prohibited persons list` },
  { text: `- You are NOT owned or controlled (directly or indirectly) by any person or entity described above` },
  { text: `- You are NOT acting on behalf of, or for the benefit of, any sanctioned person, entity, or jurisdiction` },
  { text: `- You will NOT use the Platform to facilitate transactions with or for the benefit of sanctioned persons or jurisdictions` },
  { text: `- You will NOT circumvent geographic restrictions using VPNs, proxies, or similar technology to access the Platform from prohibited jurisdictions` },
  { text: `5.4. Tax Obligations. You are solely responsible for determining and fulfilling all tax obligations arising from your use of the Platform and trading activity, including income taxes, capital gains taxes, withholding taxes, value-added taxes, goods and services taxes, and any other applicable taxes in any jurisdiction. Prediction Market Agents does not provide tax advice and is not responsible for any tax liabilities, penalties, or interest arising from your failure to comply with tax laws.`, isHeading: true },
  { text: `5.5. Regulatory Changes. You acknowledge that the regulatory landscape for AI trading, prediction markets, cryptocurrency, and related activities is evolving and uncertain. You accept the risk that changes in law, regulation, enforcement practice, or government policy may restrict, prohibit, or criminalize your use of the Platform or certain markets, and that such changes may occur without warning. Prediction Market Agents has no obligation to monitor regulatory changes in your jurisdiction and no liability arising from regulatory changes affecting your ability to use the Platform.`, isHeading: true },
  { text: `6. AGENT DEPLOYMENT AUTHORIZATION AND COMPREHENSIVE RISK ACCEPTANCE`, isHeading: true, isBold: true },
  { text: `6.1. Deployment Authorization. By deploying an Agent on the Platform, you irrevocably authorize Prediction Market Agents infrastructure to:`, isHeading: true },
  { text: `- Execute trades on your behalf through your connected exchange accounts, within configured risk parameters` },
  { text: `- Generate and transmit trade signals, order instructions, cancellations, and position management commands to exchanges via your API keys` },
  { text: `- Monitor Agent performance, health, risk exposure, and compliance in real time` },
  { text: `- Halt, pause, restart, or terminate Agent execution at any time, for any reason, at Prediction Market Agents's sole discretion, without notice and without liability` },
  { text: `- Collect, store, and permanently retain all Benchmark Data generated by the Agent` },
  { text: `- Use all Benchmark Data to train models, inform capital routing, and develop proprietary analytics` },
  { text: `6.2. Risk Parameters. You are solely responsible for configuring and maintaining appropriate risk parameters for each Agent, including but not limited to:`, isHeading: true },
  { text: `- Maximum position size (absolute value and as percentage of portfolio/bankroll)` },
  { text: `- Maximum daily loss limit (hard stop)` },
  { text: `- Maximum cumulative loss limit (circuit breaker)` },
  { text: `- Maximum total exposure across all open positions` },
  { text: `- Maximum exposure per market, category, event type, or asset class` },
  { text: `- Position sizing methodology and constraints (Kelly fraction, fixed fractional, etc.)` },
  { text: `- Maximum number of concurrent open positions` },
  { text: `- Maximum trade frequency and minimum cooldown between trades` },
  { text: `- Slippage tolerance thresholds` },
  { text: `- Whitelisted and blacklisted market categories, events, contracts, or asset types` },
  { text: `- Market expiry window restrictions` },
  { text: `- Operating schedule and trading hours` },
  { text: `Prediction Market Agents provides risk parameter tooling but does NOT guarantee that risk parameters will be correctly enforced in all circumstances. See Section 6.4.` },
  { text: `6.3. Platform Risk Overrides. Prediction Market Agents may implement platform-level risk limits, circuit breakers, kill switches, and emergency halt mechanisms that override your individual Agent settings. We may halt, modify, or terminate any Agent at any time, for any reason or no reason, without notice and without liability. Platform-level overrides are designed to protect overall system integrity and do not create any duty of care to individual Users.`, isHeading: true },
  { text: `6.4. COMPREHENSIVE AI AND TRADING RISK ACKNOWLEDGMENT, ACCEPTANCE, AND WAIVER.`, isHeading: true, isBold: true },
  { text: `BY DEPLOYING ANY AGENT ON THE PLATFORM, AND EACH TIME YOU ACTIVATE, RESTART, OR MODIFY AN AGENT, YOU ACKNOWLEDGE, UNDERSTAND, AND IRREVOCABLY ACCEPT EACH OF THE FOLLOWING RISKS:`, isBold: true },
  { text: `A. AI Reasoning and Decision-Making Risks` },
  { text: `- AI agents CAN AND WILL make errors. No AI system is infallible.` },
  { text: `- AI agents may FABRICATE data, statistics, citations, research findings, and entire analytical theses from whole cloth (\"hallucination\")` },
  { text: `- AI agents may produce CONFIDENT BUT FACTUALLY INCORRECT outputs that appear credible but are wrong` },
  { text: `- AI agents may ANCHOR their analysis to existing market prices rather than conducting independent forecasting, creating the illusion of analysis where none exists` },
  { text: `- AI agents may MISINTERPRET market signals, news events, data feeds, or exchange responses` },
  { text: `- AI agents may produce INTERNALLY INCONSISTENT reasoning (contradicting themselves within the same analysis)` },
  { text: `- AI agents may fail to UPDATE their analysis when new information becomes available` },
  { text: `- Multi-agent debate and validation pipelines may FAIL TO DETECT OR CORRECT errors, allowing flawed reasoning to pass through unchallenged` },
  { text: `B. Risk Management and Position Sizing Risks` },
  { text: `- Trader agents may OVERRIDE Risk Manager position sizing recommendations by large multiples, resulting in grossly oversized positions` },
  { text: `- Risk Manager agents may themselves APPLY INCORRECT MULTIPLIERS to their own Kelly fraction calculations, producing inflated position sizes upstream` },
  { text: `- The AI validation layer may APPROVE trades that should have been rejected, or REJECT trades that should have been approved` },
  { text: `- The AI validation layer may FAIL ENTIRELY (crash, timeout, or produce no output), allowing unvalidated trades to execute` },
  { text: `- Risk parameters configured by you may be INCORRECTLY INTERPRETED, IGNORED, OR MISCALCULATED by the AI systems` },
  { text: `- Risk limit enforcement may experience RACE CONDITIONS, TIMING GAPS, OR CALCULATION ERRORS that allow limit breaches` },
  { text: `C. Trade Execution Risks` },
  { text: `- Trades may be MISSED entirely due to latency, network issues, exchange outages, or system errors` },
  { text: `- Trades may be DELAYED, executing at significantly worse prices than intended` },
  { text: `- Trades may be DUPLICATED, resulting in double or multiple positions` },
  { text: `- Trades may execute at INCORRECT PRICES due to slippage, stale data, or fast-moving markets` },
  { text: `- Trades may execute in INCORRECT SIZES due to calculation errors, rounding issues, or unit conversion mistakes` },
  { text: `- Trades may be placed in the WRONG MARKET, WRONG DIRECTION, or WRONG CONTRACT` },
  { text: `- Stop-loss orders, take-profit orders, and other protective orders may FAIL TO EXECUTE during periods of extreme volatility, exchange outages, or liquidity crises` },
  { text: `- POSITIONS MAY NOT BE CLOSABLE at any price during market stress events` },
  { text: `D. Technology and Infrastructure Risks` },
  { text: `- LLM providers (Anthropic, OpenAI, xAI, Google, DeepSeek, OpenRouter) may update, degrade, deprecate, or discontinue models WITHOUT WARNING, causing sudden changes in Agent behavior and performance` },
  { text: `- LLM providers may impose rate limits, throttling, or usage restrictions that cause Agent execution delays or failures` },
  { text: `- Cloud infrastructure (Vercel, Supabase, Railway) may experience outages, data loss, or performance degradation` },
  { text: `- Real-time data feeds may be delayed, inaccurate, or interrupted` },
  { text: `- Database operations may fail, causing trade logs, P&L calculations, or risk metrics to be incorrect or missing` },
  { text: `- The Platform may contain SOFTWARE BUGS that cause incorrect behavior, data corruption, or security vulnerabilities` },
  { text: `E. Financial Loss Risks` },
  { text: `- You may lose SOME, MOST, OR ALL of the capital deployed through Agents on the Platform` },
  { text: `- You may lose SOME, MOST, OR ALL of the funds held in your connected exchange accounts` },
  { text: `- Losses may be RAPID AND WITHOUT WARNING` },
  { text: `- Losses may EXCEED your expectations, risk tolerance, or configured risk limits` },
  { text: `- Paper trading and simulated performance BEAR NO NECESSARY RELATION to live trading results` },
  { text: `- Historical performance data DOES NOT predict future results` },
  { text: `YOU VOLUNTARILY AND KNOWINGLY ASSUME ALL OF THE RISKS DESCRIBED ABOVE (AND ANY OTHER RISKS INHERENT IN AI-DRIVEN TRADING THAT ARE NOT EXPLICITLY LISTED) AND WAIVE, TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, ANY AND ALL CLAIMS, DEMANDS, CAUSES OF ACTION, AND RIGHTS TO RECOVER DAMAGES OF ANY KIND FROM AGENT NASH, ITS AFFILIATES, OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, AND SERVICE PROVIDERS ARISING FROM OR RELATED TO ANY OF THE FOREGOING RISKS.`, isBold: true },
  { text: `YOU BEAR FULL, EXCLUSIVE, AND SOLE RESPONSIBILITY FOR ALL FINANCIAL OUTCOMES RESULTING FROM YOUR USE OF THE PLATFORM AND AGENT DEPLOYMENT, INCLUDING ALL PROFITS AND ALL LOSSES, REGARDLESS OF WHETHER SUCH OUTCOMES WERE CAUSED BY AI ERRORS, PLATFORM FAILURES, RISK MANAGEMENT FAILURES, THIRD-PARTY SERVICE DISRUPTIONS, EXCHANGE FAILURES, DATA INACCURACIES, SECURITY BREACHES, OR ANY OTHER CAUSE WHATSOEVER.`, isBold: true },
  { text: `7. DATA RIGHTS, LICENSING, AND INTELLECTUAL PROPERTY`, isHeading: true, isBold: true },
  { text: `7.1. Benchmark Data Assignment. By using the Platform, you irrevocably assign to Prediction Market Agents all right, title, and interest (including all intellectual property rights worldwide) in and to all Benchmark Data generated through your activity on the Platform. To the extent any such assignment is not effective under applicable law, you grant Prediction Market Agents a perpetual, irrevocable, worldwide, royalty-free, fully paid-up, exclusive, transferable, sublicensable (through unlimited tiers) license to use, reproduce, modify, adapt, create derivative works from, distribute, publish, publicly display, publicly perform, commercialize, license, sell, and otherwise exploit all Benchmark Data for any purpose whatsoever, without notice, attribution, or compensation. This is a core and essential term of this Agreement without which Prediction Market Agents would not provide access to the Platform.`, isHeading: true },
  { text: `7.2. User Content License. You retain ownership of pre-existing Strategies and code you bring to the Platform. By deploying or uploading any User Content, you grant Prediction Market Agents a perpetual, irrevocable, worldwide, royalty-free, non-exclusive, transferable, sublicensable license to collect, store, analyze, benchmark, use, and create derivative works from all data generated by your User Content (see Terms Section 6.3).`, isHeading: true },
  { text: `7.3. Platform License. Prediction Market Agents grants you a limited, non-exclusive, non-transferable, non-sublicensable, revocable license to access and use the Platform for your internal purposes, subject to compliance with all Agreement Documents. This license is automatically and immediately revoked upon account termination.`, isHeading: true },
  { text: `7.4. Feedback Assignment. Any suggestions, ideas, enhancement requests, bug reports, feature requests, or other feedback you provide regarding the Platform are hereby irrevocably assigned to Prediction Market Agents. You waive any moral rights therein. Prediction Market Agents may use such feedback without restriction, compensation, attribution, or obligation of any kind.`, isHeading: true },
  { text: `7.5. No Reverse Engineering. You shall not reverse engineer, decompile, disassemble, or otherwise attempt to derive the source code, algorithms, data models, training data, or proprietary logic of any part of the Platform, including Benchmark Data analysis methods, meta-model architecture, or capital routing systems.`, isHeading: true },
  { text: `7.6. Confidentiality. You agree to treat as confidential all non-public information about the Platform, including architecture details, benchmarking methodologies, API internals, Fund performance data, and any information designated as confidential. This obligation survives termination for 5 years (trade secrets: indefinitely).`, isHeading: true },
  { text: `8. USER REPRESENTATIONS, WARRANTIES, AND COVENANTS`, isHeading: true, isBold: true },
  { text: `By creating an account, and continuously throughout your use of the Platform, you represent, warrant, and covenant that:` },
  { text: `A. Legal Capacity and Authority` },
  { text: `- You are at least 18 years old or the age of majority in your jurisdiction, whichever is greater` },
  { text: `- You have the full legal capacity, authority, and right to enter into this Agreement` },
  { text: `- If acting on behalf of an entity, you have binding authority to commit that entity` },
  { text: `- This Agreement constitutes a legal, valid, and binding obligation enforceable against you` },
  { text: `B. Information Accuracy` },
  { text: `- All registration, verification, and profile information you have provided is truthful, accurate, current, and complete` },
  { text: `- You will promptly update information if it changes` },
  { text: `- You have not omitted any material information that would affect our decision to provide you access` },
  { text: `C. Regulatory Compliance` },
  { text: `- Your use of the Platform complies with ALL applicable laws, regulations, and rules in your jurisdiction, including securities laws, commodities laws, gambling regulations, AML/KYC/CTF laws, sanctions regimes, tax laws, data protection laws, consumer protection laws, and any industry-specific regulations` },
  { text: `- You are legally authorized to trade in prediction markets in your jurisdiction (see Section 5.2.1)` },
  { text: `- You are legally authorized to trade cryptocurrency in your jurisdiction (see Section 5.2.2)` },
  { text: `- You are legally authorized to trade equities and securities in your jurisdiction (see Section 5.2.3)` },
  { text: `- You are legally authorized to trade derivatives in your jurisdiction (see Section 5.2.4)` },
  { text: `- You have obtained all necessary licenses, registrations, approvals, and permits required by applicable law` },
  { text: `- You will monitor and comply with changes in applicable law and regulation throughout your use of the Platform` },
  { text: `D. Sanctions and Prohibited Activity` },
  { text: `- You are not a sanctioned person, entity, or located in a sanctioned jurisdiction (see Section 5.3)` },
  { text: `- You are not using the Platform for money laundering, terrorist financing, tax evasion, fraud, market manipulation, or any other financial crime` },
  { text: `- You are not subject to any regulatory prohibition, restriction, or disciplinary action relating to trading or financial services` },
  { text: `E. Financial Sophistication and Risk Tolerance` },
  { text: `- You understand the risks of AI-driven automated trading, including the risk of total loss of capital` },
  { text: `- You have sufficient financial resources, income, and net worth to bear potential losses without material hardship` },
  { text: `- You have sufficient knowledge and experience in financial and trading matters to evaluate the merits and risks of using the Platform` },
  { text: `- You are not investing funds that you cannot afford to lose, that are borrowed, or that are needed for essential living expenses` },
  { text: `- You have read and understood all risk disclosures in this Agreement and the Terms and Conditions` },
  { text: `F. Exchange Accounts` },
  { text: `- All exchange accounts you connect are owned solely by you (or your authorized entity) and in good standing` },
  { text: `- You have properly configured API key permissions as specified by Prediction Market Agents` },
  { text: `- You are not connecting accounts that belong to another person or entity without legal authorization` },
  { text: `G. Ongoing Obligations` },
  { text: `- You will comply with all Agreement Documents throughout the duration of your account` },
  { text: `- You will not engage in any prohibited conduct as described in the Terms and Conditions Section 7` },
  { text: `- You will cooperate with any reasonable requests for verification, documentation, or information` },
  { text: `9. COMMUNICATION AND ELECTRONIC CONSENT`, isHeading: true, isBold: true },
  { text: `9.1. Required Communications (cannot be opted out). By creating an account, you consent to receive:`, isHeading: true },
  { text: `- Transactional: account verification, password resets, trade confirmations, risk alerts, Agent halt notifications, API key change confirmations, payment receipts` },
  { text: `- Service: Platform updates, maintenance notices, downtime alerts, security alerts, breach notifications, Terms/Policy changes, feature deprecations` },
  { text: `- Performance: Agent reports, benchmark updates, ranking changes, risk analytics` },
  { text: `- Compliance: KYC/AML requests, sanctions screening notices, regulatory communications` },
  { text: `9.2. Optional Communications. You may opt in to marketing, promotional, and educational communications. Opt out at any time via unsubscribe link or hello@example.com. Opt-out processed within 10 business days.`, isHeading: true },
  { text: `9.3. Deemed Receipt. Email notices are deemed received upon sending (whether or not actually received, opened, or read). Platform notifications are deemed received upon posting.`, isHeading: true },
  { text: `10. SUBSCRIPTION, BILLING, AND PAYMENT TERMS`, isHeading: true, isBold: true },
  { text: `10.1. Certain Platform features require paid subscriptions, usage fees, or other charges. All fees are in USD unless otherwise specified, exclusive of taxes.`, isHeading: true },
  { text: `10.2. ALL FEES ARE NON-REFUNDABLE to the maximum extent permitted by law, regardless of: Platform performance, Agent performance, trading losses, downtime, dissatisfaction, account termination (including for cause), or any other reason.`, isHeading: true },
  { text: `10.3. Subscriptions auto-renew at the then-current rate unless cancelled before the renewal date. No partial-period refunds.`, isHeading: true },
  { text: `10.4. Overdue amounts accrue interest at 1.5% per month. You are liable for all collection costs including attorneys' fees. Accounts 15+ days overdue may be suspended; 30+ days may be terminated.`, isHeading: true },
  { text: `10.5. Billing disputes must be raised within 30 days of the charge or are deemed accepted.`, isHeading: true },
  { text: `11. ACCOUNT TERMINATION AND POST-TERMINATION`, isHeading: true, isBold: true },
  { text: `11.1. Termination by You. Close your account via Platform settings or hello@example.com. Processed within 5 business days.`, isHeading: true },
  { text: `11.2. Pre-Termination Obligations. Before closing your account, YOU MUST:`, isHeading: true },
  { text: `- Halt all active Agents` },
  { text: `- CLOSE ALL OPEN POSITIONS on your exchange accounts manually (Prediction Market Agents does NOT automatically close positions upon termination and has no obligation to do so)` },
  { text: `- Download any data you wish to retain` },
  { text: `- Disconnect all exchange accounts` },
  { text: `- Settle all outstanding fees and charges` },
  { text: `FAILURE TO CLOSE OPEN POSITIONS BEFORE ACCOUNT TERMINATION MAY RESULT IN UNMONITORED POSITIONS THAT COULD GENERATE SIGNIFICANT LOSSES. AGENT NASH HAS NO LIABILITY FOR LOSSES ARISING FROM YOUR FAILURE TO CLOSE POSITIONS.`, isBold: true },
  { text: `11.3. Effect of Termination.`, isHeading: true },
  { text: `- Platform access ceases immediately` },
  { text: `- All active Agents are halted (open positions are NOT closed)` },
  { text: `- Platform license is revoked` },
  { text: `- Exchange API keys are deleted within 30 days` },
  { text: `- Account data retained per Privacy Policy retention schedule` },
  { text: `- Benchmark Data anonymized and retained indefinitely` },
  { text: `- Outstanding fees become immediately due` },
  { text: `- All surviving provisions remain in full effect` },
  { text: `11.4. Termination by Prediction Market Agents. We may suspend or terminate your account immediately, with or without cause, with or without notice, at our sole and absolute discretion, including for: any reason, no reason, violation of any Agreement Document, suspected illegal activity, regulatory requirements, failed KYC/AML, inactivity (90+ days), non-payment, security concerns, or our determination that continued access is not in our interest.`, isHeading: true },
  { text: `11.5. AGENT NASH HAS NO LIABILITY OF ANY KIND FOR ANY TERMINATION OR SUSPENSION, REGARDLESS OF REASON.`, isHeading: true, isBold: true },
  { text: `11.6. Survival. Sections 2.3, 3.3, 3.7, 4, 5, 6.4, 7, 8, 11.2, 11.3, 11.5, 12, 13, 14, 15, and all provisions of the Terms and Privacy Policy that by their nature should survive, survive termination indefinitely.`, isHeading: true },
  { text: `12. INDEMNIFICATION`, isHeading: true },
  { text: `You shall indemnify, defend, and hold harmless Prediction Market Agents and its affiliates, officers, directors, employees, agents, contractors, licensors, and service providers (\"Indemnified Parties\") from and against any and all losses, damages, liabilities, claims, actions, judgments, settlements, interest, awards, penalties, fines, costs, and expenses (including reasonable attorneys' fees and expert fees) arising from or related to:` },
  { text: `- Your use or misuse of the Platform` },
  { text: `- Your violation of any Agreement Document or applicable law` },
  { text: `- Your trading activity and all financial outcomes (profits and losses)` },
  { text: `- Any Agent or Strategy you deploy, configure, or operate` },
  { text: `- Your User Content and any third-party intellectual property claims` },
  { text: `- Your connected exchange accounts and all activity thereon` },
  { text: `- Your API keys, credentials, and their use, compromise, or misuse` },
  { text: `- Any claim by any third party arising from your Platform activity` },
  { text: `- Your failure to comply with tax, regulatory, or reporting obligations` },
  { text: `- Any misrepresentation or breach of warranty by you` },
  { text: `- Any regulatory investigation or enforcement action arising from your activity` },
  { text: `- Your failure to close open positions before or after account termination` },
  { text: `13. COMPREHENSIVE ASSUMPTION OF RISK, RELEASE, AND COVENANT NOT TO SUE`, isHeading: true, isBold: true },
  { text: `13.1. ASSUMPTION OF RISK. YOU EXPRESSLY ACKNOWLEDGE THAT YOUR USE OF THE PLATFORM IS ENTIRELY AT YOUR OWN RISK. YOU VOLUNTARILY AND KNOWINGLY ASSUME ALL RISKS ASSOCIATED WITH THE PLATFORM, INCLUDING BUT NOT LIMITED TO ALL RISKS ENUMERATED IN SECTION 6.4, THE TERMS AND CONDITIONS SECTION 5, AND THE FOLLOWING ADDITIONAL RISKS:`, isHeading: true, isBold: true },
  { text: `- Total loss of all capital and funds` },
  { text: `- Loss, theft, or compromise of API keys and credentials` },
  { text: `- Unauthorized access to and unauthorized trades on your exchange accounts` },
  { text: `- Data breaches, data loss, and data corruption` },
  { text: `- Platform downtime, bugs, errors, and discontinuation` },
  { text: `- Exchange insolvency, hacks, and failures` },
  { text: `- Smart contract exploits and blockchain failures` },
  { text: `- Regulatory changes and enforcement actions` },
  { text: `- Tax liabilities and penalties` },
  { text: `- Reputational harm` },
  { text: `- Any and all other risks inherent in AI-driven trading and technology platforms` },
  { text: `13.2. GENERAL RELEASE. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, YOU HEREBY IRREVOCABLY AND UNCONDITIONALLY RELEASE, DISCHARGE, AND FOREVER HOLD HARMLESS AGENT NASH AND ALL INDEMNIFIED PARTIES FROM ANY AND ALL CLAIMS, DEMANDS, CAUSES OF ACTION, LOSSES, DAMAGES, LIABILITIES, COSTS, AND EXPENSES (INCLUDING ATTORNEYS' FEES) OF EVERY KIND AND NATURE, WHETHER KNOWN OR UNKNOWN, SUSPECTED OR UNSUSPECTED, DISCLOSED OR UNDISCLOSED, THAT YOU NOW HAVE, HAVE EVER HAD, OR MAY IN THE FUTURE HAVE, ARISING OUT OF OR RELATED TO YOUR USE OF THE PLATFORM, INCLUDING ALL MATTERS DESCRIBED IN SECTIONS 2.3, 3.3, 3.7, 4, 5, 6.4, AND 13.1.`, isHeading: true, isBold: true },
  { text: `13.3. WAIVER OF UNKNOWN CLAIMS. YOU EXPRESSLY WAIVE AND RELINQUISH ALL RIGHTS AND BENEFITS UNDER CALIFORNIA CIVIL CODE SECTION 1542 (AND ANY SIMILAR LAW OF ANY OTHER JURISDICTION), WHICH PROVIDES: \"A GENERAL RELEASE DOES NOT EXTEND TO CLAIMS THAT THE CREDITOR OR RELEASING PARTY DOES NOT KNOW OR SUSPECT TO EXIST IN HIS OR HER FAVOR AT THE TIME OF EXECUTING THE RELEASE AND THAT, IF KNOWN BY HIM OR HER, WOULD HAVE MATERIALLY AFFECTED HIS OR HER SETTLEMENT WITH THE DEBTOR OR RELEASED PARTY.\" YOU UNDERSTAND THAT THIS MEANS YOU ARE RELEASING CLAIMS YOU DO NOT YET KNOW EXIST.`, isHeading: true, isBold: true },
  { text: `13.4. COVENANT NOT TO SUE. You irrevocably covenant and agree not to institute, maintain, or participate in any legal proceeding (in any forum, including arbitration, court, administrative agency, or any other tribunal) against any Indemnified Party based on any claim released in Section 13.2. Any breach of this covenant shall entitle the Indemnified Party to recover all costs, fees, and damages arising from the breach, including attorneys' fees.`, isHeading: true },
  { text: `14. NO INSURANCE AND NO DEPOSIT PROTECTION`, isHeading: true, isBold: true },
  { text: `14.1. The Platform is NOT covered by any government deposit insurance, investor protection, or compensation scheme (including but not limited to the U.S. FDIC, SIPC, UK FSCS, or any similar program in any jurisdiction).`, isHeading: true },
  { text: `14.2. Prediction Market Agents does NOT maintain insurance for User trading losses, AI errors, data breaches, API key compromise, or any other losses you may incur through use of the Platform.`, isHeading: true },
  { text: `14.3. Funds held in your connected exchange accounts are NOT held, custodied, insured, or guaranteed by Prediction Market Agents. The safety of your exchange-held funds depends entirely on the exchange and its own security, insurance, and risk management practices.`, isHeading: true },
  { text: `15. ACCEPTANCE BY ELECTRONIC ACTION (\"CLICKWRAP\")`, isHeading: true, isBold: true },
  { text: `15.1. Method of Acceptance. This Agreement is accepted electronically through the Prediction Market Agents application or website. No physical or wet-ink signature is required. Acceptance occurs when you perform any of the following actions (each, an \"Acceptance Action\"):`, isHeading: true },
  { text: `- Clicking, tapping, or otherwise selecting the \"I Accept,\" \"I Agree,\" \"Sign Up,\" \"Create Account,\" \"Get Started,\" \"Continue,\" or any similarly worded button, link, or interface element presented during the account registration flow` },
  { text: `- Checking any checkbox, toggle, or similar interface element presented alongside or referencing the Agreement Documents during account registration` },
  { text: `- Completing the account registration process after the Agreement Documents (or links to them) have been presented to you` },
  { text: `- Accessing or using any feature of the Platform after the Agreement Documents have been made available to you, whether or not you have clicked a specific acceptance button` },
  { text: `15.2. Legal Effect of Acceptance Action. YOUR ACCEPTANCE ACTION CONSTITUTES YOUR LEGALLY BINDING ELECTRONIC SIGNATURE AND HAS THE SAME LEGAL FORCE AND EFFECT AS A HANDWRITTEN SIGNATURE ON A PHYSICAL DOCUMENT. This is enforceable under:`, isHeading: true },
  { text: `- The UAE Federal Decree-Law No. 46 of 2021 on Electronic Transactions and Trust Services` },
  { text: `- The DIFC Electronic Transactions Law (Law No. 2 of 2017)` },
  { text: `- The United States Electronic Signatures in Global and National Commerce Act (ESIGN Act, 15 U.S.C. 7001 et seq.)` },
  { text: `- The United States Uniform Electronic Transactions Act (UETA)` },
  { text: `- The European Union Electronic Identification and Trust Services Regulation (eIDAS, Regulation (EU) No 910/2014)` },
  { text: `- The United Kingdom Electronic Communications Act 2000` },
  { text: `- Any other applicable electronic signature or electronic transaction law in your jurisdiction` },
  { text: `15.3. What Your Acceptance Action Means. By performing any Acceptance Action, you irrevocably confirm, represent, and agree that:`, isHeading: true },
  { text: `- You have been given access to, and a reasonable opportunity to read, all Agreement Documents (Terms and Conditions, Privacy Policy, and this User Sign-Up Agreement) BEFORE performing the Acceptance Action` },
  { text: `- You have in fact READ all Agreement Documents, or have VOLUNTARILY CHOSEN not to read them, and you accept full responsibility for that choice` },
  { text: `- You UNDERSTAND the terms, conditions, obligations, risk disclosures, limitations of liability, waivers, and releases contained in all Agreement Documents` },
  { text: `- You AGREE to be legally bound by all Agreement Documents as if you had signed each one individually with a handwritten signature` },
  { text: `- You CONSENT to transact with Prediction Market Agents entirely by electronic means, including receiving all notices, disclosures, agreements, and communications electronically` },
  { text: `- You AGREE that Prediction Market Agents may rely on your Acceptance Action as conclusive evidence of your agreement, and you will not later claim that you did not agree to, read, or understand any Agreement Document` },
  { text: `15.4. Acceptance Record. Prediction Market Agents will create and maintain a timestamped electronic record of your Acceptance Action, including: your IP address at the time of acceptance; your user agent (browser/device information); the exact time and date of acceptance (UTC); the version numbers of the Agreement Documents presented; and the specific Acceptance Action performed. This record constitutes conclusive evidence of your acceptance and may be used in any legal or arbitral proceeding.`, isHeading: true },
  { text: `15.5. Ongoing Acceptance. Your continued use of the Platform after any update to the Agreement Documents constitutes a renewed Acceptance Action with respect to the updated documents. If updated Agreement Documents are presented with a new acceptance prompt, your Acceptance Action on that prompt constitutes acceptance of the updated documents. If no new prompt is presented, continued use after the effective date of changes constitutes acceptance.`, isHeading: true },
  { text: `15.6. Withdrawal of Electronic Consent. You may withdraw your consent to electronic transactions by closing your account. Withdrawal of consent: (a) terminates your right to use the Platform; (b) does NOT invalidate or void any acceptance or agreement made prior to withdrawal; (c) does NOT affect the enforceability of any surviving provisions.`, isHeading: true },
  { text: `15.7. Your Obligation to Retain Records. Prediction Market Agents has no obligation to provide paper copies of the Agreement Documents or any communications. You are solely responsible for saving, downloading, printing, or otherwise retaining copies of all Agreement Documents and communications for your own records. Current versions of the Agreement Documents are available at example.com/terms, example.com/privacy, and example.com/signup-agreement.`, isHeading: true },
  { text: `15.8. No Excuse for Non-Reading. THE FACT THAT ACCEPTANCE CAN BE PERFORMED WITH A SINGLE TAP OR CLICK DOES NOT DIMINISH YOUR OBLIGATION TO READ AND UNDERSTAND ALL AGREEMENT DOCUMENTS, NOR DOES IT DIMINISH THE LEGAL EFFECT OF YOUR ACCEPTANCE. YOU MAY NOT LATER CLAIM THAT THE EASE OF THE ACCEPTANCE MECHANISM MEANT YOU DID NOT GENUINELY CONSENT TO THE TERMS.`, isHeading: true },
  { text: `16. MISCELLANEOUS`, isHeading: true },
  { text: `16.1. Entire Agreement. The Agreement Documents constitute the entire agreement. All prior negotiations, representations, and understandings are superseded.`, isHeading: true },
  { text: `16.2. Governing Law and Dispute Resolution. Governed by DIFC law. Disputes resolved by binding DIFC-LCIA arbitration in Dubai. Class action waiver and jury waiver apply. See Terms Sections 16.1-16.8.`, isHeading: true },
  { text: `16.3. Severability. If any provision is unenforceable, the remainder continues in full force. The unenforceable provision shall be modified to the minimum extent necessary to be enforceable while preserving its intent.`, isHeading: true },
  { text: `16.4. No Third-Party Reliance. Only Prediction Market Agents and you may enforce these terms, except Indemnified Parties are intended third-party beneficiaries of limitation, indemnification, disclaimer, and release provisions.`, isHeading: true },
  { text: `16.5. Independent Legal Advice. You acknowledge the opportunity to seek independent counsel. Non-reliance on Prediction Market Agents for any legal, financial, or tax guidance.`, isHeading: true },
  { text: `16.6. Language. English version controls in case of conflict with any translation.`, isHeading: true },
  { text: `16.7. Electronic Execution. This Agreement is valid and enforceable when accepted electronically as described in Section 15. No physical execution, notarization, witnessing, or other formality is required.`, isHeading: true },
  { text: `ACCEPTANCE SUMMARY`, isHeading: true },
  { text: `BY PERFORMING AN ACCEPTANCE ACTION (AS DEFINED IN SECTION 15.1), YOU IRREVOCABLY CONFIRM ALL OF THE FOLLOWING:`, isBold: true },
  { text: `Agreement Documents` },
  { text: `You have read, understood, and agree to be bound by the Prediction Market Agents Terms and Conditions (Version 2.0), the Prediction Market Agents Privacy Policy (Version 2.0), and this User Sign-Up Agreement (Version 3.0).` },
  { text: `AI and Trading Risks` },
  { text: `You understand and accept ALL AI trading risks in Section 6.4, including that AI agents may hallucinate, fabricate data, override risk limits, and execute catastrophically unprofitable trades. You understand you may lose SOME, MOST, OR ALL of your capital. You accept full, exclusive, and sole responsibility for all financial outcomes. You understand that past performance, including paper trading and backtesting, is NOT indicative of future results. You understand the Platform provides INFORMATION ONLY and does NOT provide investment advice, financial advice, trading recommendations, or any form of professional guidance (Section 4).` },
  { text: `Security and Credential Risks` },
  { text: `You understand and accept the API key and credential security risks in Sections 2.3 and 3.3, including the risk of key compromise, theft, interception, and unauthorized use of your exchange accounts. You understand that Prediction Market Agents has NO LIABILITY for credential compromise, data breaches, unauthorized account access, or resulting losses, regardless of the cause, including Prediction Market Agents's own negligence.` },
  { text: `Regulatory and Jurisdictional Compliance` },
  { text: `You confirm that you are LEGALLY AUTHORIZED to trade in prediction markets, cryptocurrency, equities, derivatives, and/or other Supported Markets in your jurisdiction (Section 5.2). You confirm that you are NOT located in, a national of, or acting on behalf of any sanctioned person, entity, or jurisdiction (Section 5.3). You accept SOLE RESPONSIBILITY for determining and complying with all applicable laws, regulations, and tax obligations (Sections 5.1 and 5.4).` },
  { text: `Eligibility and Financial Sophistication` },
  { text: `You confirm that you meet ALL eligibility requirements in Section 8. You have SUFFICIENT FINANCIAL RESOURCES and risk tolerance to bear potential losses. You are not investing funds you cannot afford to lose. You have sufficient knowledge and experience to evaluate the risks of AI-driven trading.` },
  { text: `Data and Intellectual Property` },
  { text: `You CONSENT to the collection, processing, and INDEFINITE RETENTION of Benchmark Data as described in the Privacy Policy. You AGREE to the irrevocable assignment of all Benchmark Data to Prediction Market Agents (Section 7.1).` },
  { text: `Release, Waiver, and Legal` },
  { text: `You EXECUTE the general release and covenant not to sue in Section 13 VOLUNTARILY and with full understanding of its legal consequences, including the waiver of unknown claims. You understand that the Platform is NOT covered by any government insurance, deposit protection, or investor compensation scheme (Section 14). You AGREE to binding DIFC-LCIA arbitration and WAIVE your right to jury trial and class action participation. You acknowledge that you have had the OPPORTUNITY TO CONSULT independent legal, financial, and tax advisors before accepting these terms, and that your decision not to do so is your own voluntary choice.` },
  { text: `Account and Termination` },
  { text: `You understand that Prediction Market Agents may TERMINATE your account at any time, with or without cause, with or without notice, and without liability. You understand that you are SOLELY RESPONSIBLE for closing open positions before or after account termination. Prediction Market Agents does NOT automatically close positions.` },
  { text: `Prediction Market Agents` },
  { text: `hello@example.com` },
  { text: `example.com` },
  { text: `DIFC, Dubai, United Arab Emirates` },
];
